# Equal-parameter SwiGLU ablation of minimind_pretrain_60m.py.
# GELU uses two 768x3072 FFN matrices; SwiGLU uses three 768x2048 matrices,
# keeping the FFN parameter count equal while changing only the FFN method.
model = dict(
    vocab_size=6400,
    block_size=768,
    n_layer=8,
    n_head=8,
    d_model=768,
    d_ff=2048,
    dropout=0.1,
    attention_type="mha",
    ffn_type="swiglu",
    position_embedding_type="learned_absolute",
)

train = dict(
    data_dir="data/minimind/pretrain_mini",
    tokenizer="minimind",
    out_dir="checkpoints/minimind_pretrain_swiglu_60m",
    batch_size=128,
    gradient_accumulation_steps=2,
    target_tokens_per_step=196608,
    max_steps=6400,
    eval_interval=200,
    eval_batches=30,
    log_interval=10,
    learning_rate=4e-4,
    min_lr=4e-5,
    warmup_steps=500,
    weight_decay=0.1,
    grad_clip=1.0,
    dtype="bfloat16",
    compile=True,
    fused_optimizer=True,
    seed=1337,
    wandb_mode="online",
    wandb_entity="Zjunlp-Xubqpanda",
    wandb_project="Memory-Model",
    wandb_run_name="minimind-pretrain-mini-60m-swiglu",
    wandb_tags=["ablation", "minimind", "pretrain", "60m", "mha", "swiglu"],
    wandb_init_timeout=30,
    wandb_fallback_offline=True,
)
