model = dict(
    vocab_size=6400,
    block_size=768,
    n_layer=8,
    n_head=8,
    d_model=768,
    d_ff=3072,
    dropout=0.1,
)

train = dict(
    data_dir="data/minimind/sft_mini_smoke",
    tokenizer="minimind",
    init_from="checkpoints/minimind_pretrain_full_60m/best.pt",
    out_dir="checkpoints/minimind_sft_smoke",
    epochs=1,
    batch_size=2,
    gradient_accumulation_steps=1,
    eval_interval=1,
    eval_batches=1,
    log_interval=1,
    learning_rate=1e-5,
    min_lr=1e-6,
    warmup_steps=1,
    weight_decay=0.1,
    grad_clip=1.0,
    dtype="bfloat16",
    compile=False,
    fused_optimizer=True,
    seed=1337,
    wandb_mode="disabled",
    wandb_project="Memory-Model",
    wandb_run_name="minimind-sft-smoke",
)
